plugins {
    id 'com.android.application'
}

android {
    namespace 'com.neurograf.excavatorpro'
    compileSdk 35

    defaultConfig {
        applicationId 'com.neurograf.excavatorpro'
        minSdk 23
        targetSdk 35
        versionCode 151306
        versionName '15.13.6'
    }

    buildTypes {
        release {
            minifyEnabled false
            shrinkResources false
        }
        debug {
            versionNameSuffix '-debug'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
