plugins {
    id 'com.android.application'
}

android {
    namespace 'com.jyotisha.darpana'
    compileSdk 35

    defaultConfig {
        applicationId 'com.jyotisha.darpana'
        minSdk 24
        targetSdk 35
        versionCode 44
        versionName '3.4.4'
    }

    buildTypes {
        release {
            minifyEnabled false
            shrinkResources false
        }
    }
}
